### ISSUE TITLE
Busy pin ?

### ISSUE THREAD

**Issue by ghost** [Critters/MP3FLASH16P#3]
Hi,

Which is the BUSY pin ??

I had a look to .cpp and .h  files and it seems it's not defined (maybe I need to clean again my glasses)

Thanks for helping.
Rafa.

**Comment by rsispal** [comment]
I believe it's defined by you using `.init(busyPin)`. See the simple example.

**Comment by ghost** [comment]
Hi there,

Yep,...

myPlayer.init(3);

I didn't see it at the first look...   8(

Now it works really fine.

Thanks,
Rafa.
